### ISSUE TITLE
Mod manager crashes upon clicking ANYTHING

### ISSUE THREAD

**Issue by That1M8Head** [CarJem/S3A.I.R-ModManager#5]
Whenever you click anything in the mod manager, an error pops up with an enormous amount of log information and the program quits.

**Comment by CarJem** [comment]
Can I please get both the latest log file and a screenshot of the error?

**Comment by SpeedStriker243** [comment]
Where would the log file be stored? Thanks for replying.

**Comment by SpeedStriker243** [comment]
Would this help? https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/

**Comment by GatoSoft-Software** [comment]
Hi. I've the same issue. I've Windows 10 20H2 with all it's software updated (including .NET Framework to 4.8) and I can hardly get to enable/disable some mods, but I can't do anything else because it keeps crashing with the exact same error that @jrmoserbaltimore posted above.
I hope this can be fixed soon.
Thanks in advance.  👍

**Comment by AeriaVelocity** [comment]
I guess it doesn't matter anyway, since S3AIR has built-in mod support now.
